### ISSUE TITLE
Deleting a grouped revision only deletes a single revision

### ISSUE THREAD

**Issue by rubenvanerk** [Samuell1/revisions-plugin#19]
When hitting delete on a grouped revision, only one of them actually gets deleted.
I would expect that all revisions are deleted.

cc @evwerkz

**Comment by evwerkz** [comment]
@rubenvanerk 
I don't really get it. If I want to delete all revisions of a model object, it works just as well as individual ones. Do you mean everything, the whole table?

This currently works without any problems in my two projects.

![2020-10-19 11-02-32_1](https://user-images.githubusercontent.com/49227960/96426058-0698b000-11fd-11eb-853e-2a7520adf52f.gif)

**Comment by rubenvanerk** [comment]
Try to do more than one change before saving the post. Then in the revision history these changes will be grouped. When you choose to delete a grouped revision, only one of the actually gets deleted.

**Comment by evwerkz** [comment]
I get it.

**Comment by evwerkz** [comment]
@rubenvanerk 

I tested something and on the table no information when changes are a group.
Only via the fields created_at and updated_at

![image](https://user-images.githubusercontent.com/49227960/96428011-8e7fb980-11ff-11eb-80be-f35c888224e2.png)

How would it be with?
First search and delete with created_at?

I find a code how to group revisions.
` if (input('restore_all')) {
            $revisions = Revision::where('user_id', $revision->user_id)
                ->where('created_at', $revision->created_at)->get();
        }`

I don't have any other idea now

**Comment by rubenvanerk** [comment]
Yeah, you can see it here too that they are grouped by `created_at` and `user_id`:
https://github.com/Samuell1/revisions-plugin/blob/d33e2808a17ce247030822c3b314d1b8328f841e/formwidgets/RevisionHistory.php#L130

It's not perfect so if you know another method I'm all ears :)

**Comment by evwerkz** [comment]
I tested with:

`if ($revision = Revision::where('id', input('revision_id'))->first()) {
            Db::table('system_revisions')->where([
                ['revisionable_id', $revision->revisionable_id],
                ['created_at', $revision->created_at],
            ])->delete();
            Flash::success(Lang::get('samuell.revisions::lang.messages.successfully_deleted'));
        } `

and that worked.

But I think just grouping by date is not a good thing.
I will think about it.

**Comment by evwerkz** [comment]
I'm making a new pull request to resolve it.

**Comment by rubenvanerk** [comment]
Resolved by https://github.com/Samuell1/revisions-plugin/pull/20
