### ISSUE TITLE
Method locale does not exist.

### ISSUE THREAD

**Issue by ref** [Samuell1/revisions-plugin#21]
Hi! I got error :(

<img width="1182" alt="Screenshot 2020-11-16 at 18 28 02" src="https://user-images.githubusercontent.com/505388/99247487-98fe9480-2839-11eb-9aec-fb8a6239ea7e.png">

Problem in view file _revisionhistory.htm at string 44:

`<?= $record->created_at->locale(Lang::getLocale())->isoFormat('LLL') ?>`

**Comment by rubenvanerk** [comment]
Hi!
I don't have this problem. What version of Carbon are you using? I think you have version 1 installed while this method required version 2.

**Comment by ref** [comment]
> Hi!
> I don't have this problem. What version of Carbon are you using? I think you have version 1 installed while this method requires version 2.

I use standart installation October version 469

**Comment by Samuell1** [comment]
@rubenvanerk Hey, its there a way to make it backwards compatible for now till 1.1.X OCMS isnt released?
