### ISSUE TITLE
Displaying a changed checkboxlist, radio and displaying richeditor without tags

### ISSUE THREAD

**Issue by makhlukgod** [Samuell1/revisions-plugin#24]
When you make a types (checkboxlist, radio ) revisionable, only the changed ID will be displayed. Also with tags for richeditor.  It is very uncomfortable.
If you add the ability to fix it, I will be very grateful.

**Comment by rubenvanerk** [comment]
Did you try this: https://github.com/Samuell1/revisions-plugin#displaying-a-changed-relation ?

**Comment by makhlukgod** [comment]
> Did you try this: https://github.com/Samuell1/revisions-plugin#displaying-a-changed-relation ?

This is not it.
look at this https://github.com/Samuell1/revisions-plugin/pull/25
