### ISSUE TITLE
SQL error due to ->groupBy in getHistory() method

### ISSUE THREAD

**Issue by PubliAlex** [Samuell1/revisions-plugin#26]
Hello,

I'm testing your module, you did a great job to provide the missing UI to the revisionable octobercms trait.

However, I got a bug after applying it to one of my model : 

> SQLSTATE[42000]: Syntax error or access violation: 1055 'bdd.system_revisions.id' isn't in GROUP BY (SQL: select * from `system_revisions` where `system_revisions`.`revisionable_id` = 21 and `system_revisions`.`revisionable_id` is not null and `system_revisions`.`revisionable_type` = Acme\Blog\Models\Post group by `created_at`, `user_id` order by `created_at` desc)

I would find a quick fix by commenting this line in getHistory() method of your RevisionHistory form widget : 

    ->groupBy('created_at', 'user_id')

Best regards

**Comment by chrisvidal** [comment]
got same related sql erropr issue

```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'oc-azalea.system_revisions.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select * from `system_revisions` where `system_revisions`.`revisionable_id` = 1 and `system_revisions`.`revisionable_id` is not null and `system_revisions`.`revisionable_type` = azalea.product group by `created_at`, `user_id` order by `created_at` desc)
```

**Comment by chrisvidal** [comment]
more solutions to solve this issue here:

https://stackoverflow.com/questions/43776758/how-can-i-solve-incompatible-with-sql-mode-only-full-group-by-in-laravel-eloquen

**Comment by Samuell1** [comment]
@chrisvidal Thanks a lot solved in develop hope in few days/hours there will be new version with fixes.
