### ISSUE TITLE
Date always detected as a change in the revision

### ISSUE THREAD

**Issue by PubliAlex** [Samuell1/revisions-plugin#27]
Hello,

I have a model with a date field, each time I save that model, a revision change is detected, even if I don't change anything

![image](https://user-images.githubusercontent.com/55833027/155806481-6f7686c7-8d88-4a5e-b31d-e8f433d34bdd.png)

my database table is of type : "date"

![image](https://user-images.githubusercontent.com/55833027/155806562-8c73c391-b210-48c7-bcae-220f766fd2df.png)

and my field is a standard datepicker

![image](https://user-images.githubusercontent.com/55833027/155806773-55b8355d-e9e2-4c17-8659-0f3c4f07be96.png)

Best regards,

Alex

**Comment by Samuell1** [comment]
Hey, thanks this looks like OCMS issue because iam using theirs trait.
