### ISSUE TITLE
Checkbox in popup are not visibles

### ISSUE THREAD

**Issue by PubliAlex** [Samuell1/revisions-plugin#28]
Hello,

When you open a revision popup, checkbox are not visibles (october 2)

![image](https://user-images.githubusercontent.com/55833027/155807539-8df10ca1-625a-4ae0-a51f-4a6cb9cccbac.png)

Best regards,

**Comment by chrisvidal** [comment]
this is a OC v2 stylesheet issues, not this plugin issue
