### ISSUE TITLE
Alter the output before rendering

### ISSUE THREAD

**Issue by PubliAlex** [Samuell1/revisions-plugin#29]
Hello,

Is it possible to alter the output of a field before rendering it ? 

Because repeater fields render very badly and I would like to be able to deal with it before display it

![image](https://user-images.githubusercontent.com/55833027/155835645-5113a60f-65a3-4019-9e9b-8881f2336dd6.png)

Also, it would be great to not escape content when displaying it in partial like here : 

`<?= $getFieldDiff($revision->field, e($revision->old_value), e($revision->new_value)) ?>`

And let user display html if they need to

Thank you

**Comment by Samuell1** [comment]
Hey, only option for repeater fields is to create custom handler but without reworking whole its not possible.
