### ISSUE TITLE
Issue with rendering of changed RichTextEditor field

### ISSUE THREAD

**Issue by chrisvidal** [Samuell1/revisions-plugin#31]
the plugin detects where there is not in the case of RichTextEditor.

![image](https://user-images.githubusercontent.com/2263496/162383379-438ee690-140c-4ad2-872e-e25cf976cf2e.png)

**Comment by chrisvidal** [comment]
the issue appears only at the fist saving.
the 1st save seems to triggers all the revisionable declared field to have changed even when they didnt

**Comment by Samuell1** [comment]
Hey, this looks like issue how richeditor handles saving.
